// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "ghost":return img`
........................
........................
........................
........................
..........fffff.........
........ff11111f........
.......fb111111bf.......
......fbd1111111f.......
......fddd111111df......
......fdddd11111df......
......fddddddd11df......
......fddddddd111f......
......fddddddcf11f......
.......fbdddb1111bf.....
........fffcfdb1b1f.....
.......ffffffffbfbf.....
....ff.fffffffffff......
.....ffffffff...........
.....ffffffb1b1f........
......ffffffbfbf........
........................
........................
........................
........................
`;
            case "image2":
            case "ghosty":return img`
........................
........................
........................
........................
..........fffff.........
........ff11111f........
.......fb111111bf.......
......fbd1111111f.......
......fddd111111df......
......fdddd11111df......
......fddddddd11df......
......fddddddd111f......
......fddddddcf11f......
.......fbdddb1111bf.....
........fffcfdb1b1f.....
.......ffffffffbfbf.....
....ff.fffffffffff......
.....ffffffff...........
.....ffffffb1b1f........
......ffffffbfbf........
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
